### ISSUE TITLE
Commencer à Incarnam

### ISSUE THREAD

**Issue by liberodark** [Sarazar928Ghost/HelpGame#1]
Bonjour,

Il serait bien de commencer à incarnam devant la statue de chaque classe pour tout les nouveaux perso créé de niveau 1.

Cordialement

**Comment by Sarazar928Ghost** [comment]
Cela y est déjà implémenté.
Il suffit de laisser la ligne START_PLAYER vide.
Exemple : START_PLAYER = 

A la sortie de la version 1.40.13 cela sera spécifié dans la config.
